### ISSUE TITLE
Game Logic Schema

### ISSUE THREAD

**Issue by PhantomLel** [Leek727/ChessSchedule#10]
```
event: pairings
{
   round : round_number,
   pairings : [[
	{
		name : "",
		uuid : player_uuid,
		elo : "elo",
		whatever_else : ""
	},
	{
		name : "",
		uuid : player_uuid,
		elo : "elo",
		whatever_else : ""
	}
   ]]
}

Pairings should be a list of lists that contain two player objects.
This method can cut down the number of events we have because both the admin and the players can use this same event. 

event: 'game_result'
{
   room_uuid : room_uuid,
   player_uuid : "the client's uuid",
   result : "winner uuid" or "draw" or "bye"
}

event 'game_result_res' 
{
   status : "either success or fail"
}
This event should be sent after both game results from both players have been sent and confirmed to be the same. 

event: 'round_results'
{
   results : [
         // im not sure what best way to do this is but somehow return list of who won and who lost this round
   ]
}

Obviously server needs to ensure validity of request and uuids. The server should wait for both players in the match to send this request. This event will be sent at the end of each round and signify the start of a new round.
```
### Logic

`start_game -> start_game_res`

Create pairings then send `pairings` event to clients. This indicates start of round.

Wait for `game_result` from every player. This is sent from the client and contain who won the pairing

Change elo.

Once all players have reported their match, emit `round_results` to indicate end of round.
Once confirmed, send another `pairings` event to cycle through to another round.

**Comment by clayrock78** [comment]
@PhantomLel Could you specify the sender/receiver portion of the schemata you've laid out?

**Comment by PhantomLel** [comment]
Yes I added it to the logic

**Comment by clayrock78** [comment]
@PhantomLel 
There is a problem in the front end. The "result" argument of game_result is currently sending the USERNAME of the winner, instead of the UUID of the player.

**Comment by PhantomLel** [comment]
@clayrock78 thanks for finding that I will fix it up.

**Comment by PhantomLel** [comment]
Ok I fixed that. There seems to be another backend issue.

**Comment by clayrock78** [comment]
>  There seems to be another backend issue.

Fixed

**Comment by clayrock78** [comment]
An implementation for round_results...
```
event: 'round_results'
{
   results : [
         [winner's name, loser's name],
         ... (for each match)
         [bye player's name]
   ]
}
```
Let me know if this works for you before I implement it.

**Comment by PhantomLel** [comment]
Yes that works. Thanks!
