### ISSUE TITLE
Reconnection for Player and Host

### ISSUE THREAD

**Issue by PhantomLel** [Leek727/ChessSchedule#14]
```
event: 'reconnect_player'
{
   room_uuid : roomUUID,
   player_uuid : playerUUID
}

event: 'reconnect_player_res'
{
    status : "200 || 500",
    state: "wait" || "pairings" || "leaderboard"

}

event: 'reconnect_host'
{
   room_uuid : roomUUID,
   host_uuid : hostUUID
}

event: 'reconnect_host_res'
{
    status : "200 || 500"
    state: "wait" || "pairings" || "leaderboard"

}

```

The reconnection events will of course be sent from the client. This HAS to be extremely reliable because it would be very very very bad if someone's phone were to turn off and the whole tournament gets messed up.

**Comment by clayrock78** [comment]
We can also used the built-in "disconnect" event in some way probably

**Comment by PhantomLel** [comment]
Note from meeting:
On `disconnect` event, change `player.disconnected` to `true`, then on reconnection, check that `player_uuid` is disconnected and send back state. 

```
event: 'get_pairings'
{
   room_uuid : room_uuid
}
```
