### ISSUE TITLE
Leaderboard Schema

### ISSUE THREAD

**Issue by Leek727** [Leek727/ChessSchedule#15]
```
event: 'leaderboard'
{
	rankings : [
		{
			name : "",
			score : [wins, draws, losses]
		}
	]
}
rankings should be a list of players from highest score to lowest
update leaderboard periodically
```

**Comment by PhantomLel** [comment]
Ok so @Leek727 I think this should be an event. When the `round_resutls` event is sent to the client at the end of a round, the client will then send a `leaderboard` event to get the current standings. Sound good?

**Comment by clayrock78** [comment]
@PhantomLel What is `round_results`? Is there a schema detailing the event? If not, what is the purpose, so that I can write the schema?

**Comment by PhantomLel** [comment]
Yes its in #10

**Comment by clayrock78** [comment]
Completed in commit 6533501650d0f2f9aa4b0c24767e4c6abbb19c86
