### ISSUE TITLE
Players join mid-game bug

### ISSUE THREAD

**Issue by clayrock78** [Leek727/ChessSchedule#23]
Right now, we allow players to join a game that is already in progress. I think that we should strive to allow players to join mid-tournament, but make sure that this doesn't break anything. It seems like this is what breaks the pairings not showing up as well as causing the "next game" button to break.

**Comment by clayrock78** [comment]
@PhantomLel Do you think "player_list_update" would break something if it is sent while the host is on the dashboard?

**Comment by PhantomLel** [comment]
No it would just do nothing

**Comment by clayrock78** [comment]
Doing that also seems to make the leaderboard show nothing... seems like something really bad is being caused by a player joining mid-game.

**Comment by PhantomLel** [comment]
Wait but why do you even need to send a player joining thing? Why don't you just add the player to the pool then whenever the round ends, it will just send the new player with the pairings.

**Comment by PhantomLel** [comment]
I can't check it right now but I'll check asap

**Comment by clayrock78** [comment]
> Wait but why do you even need to send a player joining thing? Why don't you just add the player to the pool then whenever the round ends, it will just send the new player with the pairings.

It DOES add the player to the pool (immediately, but that shouldn't cause any issues), but it sends a request to the host "player_list_update", which may be causing a problem. This may be what is breaking the pairings display.

**Comment by clayrock78** [comment]
Here's what I did to produce the bug in full effect.

# Procedure to create the bug
1. Create a game.
2. Three players join. One player is in the process of joining (entered information, but hasn't pressed the "Join" button).
3. Host begins the game.

# Resultant failures
- Bye player's screen switches back to waiting ("See your name on the screen?")
- Late-joined player is also on the waiting screen
- The two non-bye, correctly joined players get an empty leaderboard as soon as they submit their results
- The above event also causes the late-joined player to see the waiting string ("See your name...") as well as the PROPER leaderboard for that round
- From here, the host can click into the next round, but the three players who joined at the proper time have broken games. The only player with the working game is the player who joined later than the others. 

# Plan
Review schemata and logic associated with 
- "get_leaderboard"
- "join_room" - we definitely need to fix this route, mainly when it's usage is allowed, or how its usage is handled at different stages of a tournament (waiting, pairings, leaderboard)
- "pairings"
- **State-changing elements**
