### ISSUE TITLE
Live Game Results

### ISSUE THREAD

**Issue by PhantomLel** [Leek727/ChessSchedule#24]
Implement live game results so that everyone can see the current state of games. This is especially useful for the moderator to know who won/lost. From this point onwards, I think we should make it so that features are implemented by one person, both back and frontend ON A SEPERATE BRANCH. If you are unable to do some part, just put it here and someone will help you.

**Comment by clayrock78** [comment]
The branch for this has been closed. We can reopen this issue when we feel the need to implement it,
