### ISSUE TITLE
Overlapping generated room codes

### ISSUE THREAD

**Issue by clayrock78** [Leek727/ChessSchedule#6]
As a quick fix, I wrote the following code
```py
class Room:
    def __init__(self, ) -> None:
        # other code was here, removed for clarity...
        # TODO this is a temporary solution - the odds of a collision are low but possible
        self.room_code = str(randint(1_000_000, 9_999_999))
```
It would be great if we found a way to generate room codes that don't overlap. This is not a high priority, obviously. Codes must be 7 digits long

**Comment by PhantomLel** [comment]
closed with [6a890d4](https://github.com/Leek727/ChessSchedule/commit/6a890d4bf30f96901a80f89278876b23fe63e8e8)
