### ISSUE TITLE
Self-Assessment and default Elo values

### ISSUE THREAD

**Issue by clayrock78** [Leek727/ChessSchedule#7]
The point of this issue is to add a self-assessment to the UI when a player joins a room. 

This will mean completing the following,
- Changing the schema for join_room to include a self-assessment variable (some integer between 1 and 5).
  - This will mean changing the socket routes for player init **(completed)**
  - also changing JS obviously
- Changing the Player class by adding a parameter for skill level, which that player's initial rating is based on **(completed)**
- Adding a UI element to select skill levels. I think it would be cool to add images of chess pieces to represent different skill levels (pawn for beginner, then bishop for intermediate, etc.), Not necessary but def bonus points if we can add that

@PhantomLel , please look over this and confirm these steps before we begin making changes. Once you do that we can make a branch to add the feature.

**Comment by PhantomLel** [comment]
Yeah great ideas. Is this high priority or can this wait until tomorrow?

**Comment by clayrock78** [comment]
> Yeah great ideas. Is this high priority or can this wait until tomorrow?

Tomorrow works

**Comment by clayrock78** [comment]
This is an expansion of a Schema from issue #5 
# Old Schema
```
event : "join_room" {
    "name" : "Jason Quang",
    "code" : "1234567" // always 7 digits long
} -> "join_room_res"
```

# New Schema
```
event : "join_room" {
    "name" : "Jason Quang",
    "code" : "1234567", // always 7 digits long
    "skill" : <int> // from 1 to 5
} -> "join_room_res"
```

# Default Elo Values
The presented values and descriptions are not set in stone, but a good starting point
| Assessment Value | Associated ELO | Title       | Description                                 |
|------------------|----------------|-------------|---------------------------------------------|
| 1                | 100            | Learning    | I just learned/am learning the rules        |
| 2                | 250            | Beginner    | I know the rules, but I haven't played much |
| 3                | 500            | Average     | I can hold my own                           |
| 4                | 700            | Experienced | I can beat most people                      |
| 5                | 900            | Skilled     | I've won competitions in the past           |
