### ISSUE TITLE
Pairing Algorithm

### ISSUE THREAD

**Issue by PhantomLel** [Leek727/ChessSchedule#8]
### What does it need to do?
Pair based on player class attributes such as elo, wins, losses, and draws.
It should not repeat pairings unless absolutely necessary. 
### Params
players : List[Player]
### Returns
List[Tuple[Player, Player]]
It is necessary for each pair to be returned as a tuple to ensure that it can easily be sent to all of the players.

**Comment by PhantomLel** [comment]
for now lets just try to get a simple version. We can add things as we see fit later

**Comment by Leek727** [comment]
future version improvements:
take in account the number of times that a pair has played each other

**Comment by clayrock78** [comment]
Don't use a done tag. Mark completed issues as closed

**Comment by clayrock78** [comment]
> future version improvements: take in account the number of times that a pair has played each other

Open a new issue for improvements, using the enhancement tag. Make sure you reference the issue when you open it like this.
This is an enhancement of issue #8
and open a new branch, as part of that issue, to make the changes.
