### ISSUE TITLE
Start Game Schema

### ISSUE THREAD

**Issue by PhantomLel** [Leek727/ChessSchedule#9]
very simple 
```
event: start_game
{
   host_uuid : uuid of host
}

event start_game_res
{
   "status" : "success or failed"
}

You of course have to make sure that the event is coming from the host of the room

event: game_started

Does not need anything in data probably. This needs to be sent to all the connected players. 
```
`start_game` will be sent from the host client e.i. the client who created the room
`game_started` will be sent from server to ALL CLIENTS, including host. Just everyone connected to the room.

**Comment by clayrock78** [comment]
@PhantomLel Could you specify in the schema the sender and receiver(s)? For example, sent from the host, sent to the host, sent from players, or sent to players.

**Comment by PhantomLel** [comment]
I got u

**Comment by PhantomLel** [comment]
@clayrock78 pls work on this love you!!

**Comment by clayrock78** [comment]
@PhantomLel Funny you mention it... finishing up now. Expect a commit in a minute or two. 👍

**Comment by PhantomLel** [comment]
Ok I will merge them if ok?

**Comment by clayrock78** [comment]
@PhantomLel Not sure what you're asking but if you're asking to merge, go right ahead.

**Comment by PhantomLel** [comment]
I mean merge back and front end

**Comment by clayrock78** [comment]
Go for it.

**Comment by PhantomLel** [comment]
@clayrock78 updated!
